### PR TITLE
Added tests for missing bonds, angles, and torsions

### LINKED ISSUE #170: Fix checks for missing parameters
@jchodera - I was under the impression from what you wrote describing your initial code that an exception would be raised if parameters were missing for any of the major required force types in a molecule (i.e. bonds, angles, torsions, LJ), but this seems not to be the case in general. I see this being done for bonds (https://github.com/open-forcefield-group/smarty/blob/master/smarty/forcefield.py#L1234) but for none of the other force terms.

I happened across this because I was starting with a specific SMIRFF and trying to make it more general, and I found that I had certain angle terms which simply HAD no angle parameters.

We'll either need to (ASAP) implement this checking, or make our basic SMIRFFs assign generic dummy parameters to all force terms and then check that these get overridden.

### PR DESCRIPTION
**Pull request by jchodera**
This adds tests for missing bonds, angles, and torsions.

Fixes #170 

@davidlmobley : Can you add tests now?

### CODE REVIEW

**Comment by jchodera** [comment]
There's a bug in bond checking. Fixing now.

**Comment by davidlmobley** [comment]
@jchodera - I just added tests. I added one testing function which checks to see that:
1. Missing bonded terms result in an exception
2. Missing angle terms result in an exception
3. Missing torsion terms result in an exception
4. Missing LJ (Nonbonded) parameters result in an exception

You don't seem to have added a check for item 4, so the tests currently fail unless this portion is commented out. Can you add a check for item 4?

**Comment by davidlmobley** [comment]
Also, can you NOT check for missing i-j-k-i torsions in three-membered rings? https://github.com/open-forcefield-group/smarty/issues/170#issuecomment-256409575

It seems that we are not currently assigning these (which is good, as that, as you point out, makes more sense!) and neither are AMBER forcefields.

**Comment by jchodera** [comment]
> You don't seem to have added a check for item 4, so the tests currently fail unless this portion is commented out. Can you add a check for item 4?

Adding now!

**Comment by jchodera** [comment]
> You don't seem to have added a check for item 4, so the tests currently fail unless this portion is commented out. Can you add a check for item 4?

Added a check for Lennard-Jones terms.

What should we do about charges? I think we can just ensure that every molecule in the `Topology` has a corresponding `OEMol` provided. Does that make sense?

**Comment by jchodera** [comment]
> Also, can you NOT check for missing i-j-k-i torsions in three-membered rings? 

`i-j-k-i` torsions are now excluded.

**Comment by jchodera** [comment]
Travis is failing to get the openeye toolkits:

```
3.23s$ pip install --pre -i https://pypi.anaconda.org/openeye/label/beta/simple openeye-toolkits && python -c "import openeye; print(openeye.__version__)"
Collecting openeye-toolkits
  Downloading https://pypi.anaconda.org/openeye/label/beta/simple/openeye-toolkits/2016.10b7/OpenEye-toolkits-2016.10b7.tar.gz
Collecting OpenEye-toolkits-python2.7-ubuntu-12.04-x64==2016.10b7 (from openeye-toolkits)
  Could not find a version that satisfies the requirement OpenEye-toolkits-python2.7-ubuntu-12.04-x64==2016.10b7 (from openeye-toolkits) (from versions: 2016.10b1, 2016.10b2, 2016.10b3, 2016.10b4, 2016.10b5, 2016.10b6)
No matching distribution found for OpenEye-toolkits-python2.7-ubuntu-12.04-x64==2016.10b7 (from openeye-toolkits)
```

**Comment by davidlmobley** [comment]
> What should we do about charges? I think we can just ensure that every molecule in the Topology has a corresponding OEMol provided. Does that make sense?

Sounds good to me.

On travis -- sometimes OpenEye's beta builds go up not simultaneously, so probably the appropriate beta is not up yet. It'll probably be up in a day or two.

**Comment by davidlmobley** [comment]
@jchodera - is this at the point where it should be merged if tests pass locally?

**Comment by jchodera** [comment]
Yes! It works for me, except for an absolutely insane number of OpenEye warnings:

```
Warning: data type mismatch found when using generic data
```

**Comment by jchodera** [comment]
But please test locally on your machine! I've only tested `smarty.tests.test_forcefield`.

**Comment by davidlmobley** [comment]
Yes, I've gotten those warnings too; I don't know where they come from (they arrived a while back when you added a larger number of tests, I think). I'll test.

**Comment by jchodera** [comment]
It has to do with replacing tag data with a different type:
https://docs.eyesopen.com/toolkits/python/oechemtk/genericdata.html

I wonder if it's connected to the fractional bonds.

**Comment by davidlmobley** [comment]
> I wonder if it's connected to the fractional bonds.

Hmm, it could be. I do use `SetData`, but I just do it to store back into bond orders the same data that was originally there (without changing its type); it's not clear to me why that would trigger this warning. (This is to allow charge calculation to NOT modify the original molecule.)

So, this is likely ignorable. I wish it were easier to suppress specific OE warnings though.

**Comment by davidlmobley** [comment]
Tests work for me though (I ran all of them!). I'll merge.

**Pull request merged**
