### PR TITLE
Correct checking for divide by zero risk when parsing "trajectory" file in score_utils

### PR DESCRIPTION
**Pull request by bannanc**
I am making a PR so we can determine why the nightly tests are failing. I made a small change to a line in the README so github would let me make a PR, but it isn't that important.

### CODE REVIEW

**Comment by bannanc** [comment]
Here is the error we are getting:

```
======================================================================
ERROR: Test elemental atomtype sampler for hydrogen
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test/lib/python3.5/site-packages/smarty/tests/test_sampler.py", line 79, in test_atomtyper_elemental
    atomtype_sampler.run(5, traj)
  File "/home/travis/miniconda/envs/test/lib/python3.5/site-packages/smarty/sampler.py", line 912, in run
    timeseries = load_trajectory( trajFile )
  File "/home/travis/miniconda/envs/test/lib/python3.5/site-packages/smarty/score_utils.py", line 68, in load_trajectory
    timeseries[iteration][reftype]['fraction'] = timeseries[iteration][reftype][numerator]/den
ZeroDivisionError: float division by zero
```

The `den` here should be the number of reference types. The only time this is zero is if there are no reference types. A situation which should be caught in the code here, is the part of [`score_utils.load_trajectory`](https://github.com/open-forcefield-group/smarty/blob/master/smarty/score_utils.py#L66) that seems to be causing the problem. 
This seems to only be happening in python3, but my guess is that is due in part to the random nature of example simulations.

**Comment by bannanc** [comment]
I'll try to run some tests locally and see if the same thing ever happens there...

**Comment by bannanc** [comment]
I can't reproduce this locally, I tried starting a new conda environment only installing smarty and its dependencies and tests all pass locally.

**Comment by jchodera** [comment]
That's my guess too. I'd just modify [these lines](https://github.com/open-forcefield-group/smarty/blob/master/smarty/score_utils.py#L67-L68) to not divide by zero if `den` is zero.

**Comment by bannanc** [comment]
@jchodera @davidlmobley or @camizanette 
This is probably a better approach to this section of the code, could someone do a review?

**Review by davidlmobley — APPROVED** [review]
Thanks, @bannanc .

**Pull request merged**
