### PR TITLE
Clean up conversion utilities already moved to openforcefield

### PR DESCRIPTION
**Pull request by davidlmobley**
Partially resolving #244 by removing `utilities` which has been moved to github.com/open-forcefield-group/openforcefield. Much more still to be done, but this removes some key duplication.

### CODE REVIEW

**Comment by davidlmobley** [comment]
@bannanc - after opening this, I realized I perhaps went slightly too far, as these two files might actually belong in `smarty`:

> * `filter_molecule_sets/` - code used to filter DrugBank database including some initial subsets that were not used in final smarty/smirky testing
> * `oeb-to-FF-and-tripos-mol2.py` - utility to convert oeb file with parm@Frosst atomtypes to two `*.mol2` files with tripos and parm@frosst atomtypes

Do these belong here, or with the forcefield stuff?

**Comment by bannanc** [comment]
@davidlmobley 

I think the molecule sets probably make the most sense to be here actually, including the oeb to mol2 script. We use them to test the smarty and smirky simulations, but they've also been used when developing the smirnoff force field

**Comment by davidlmobley** [comment]
Thanks, @bannanc . Restored them here. Can you do a quick check when you have a chance then merge? (See also parallel PR https://github.com/open-forcefield-group/openforcefield/pull/10 -- with these two, everything in `utilities` should now be only in one place rather than two.)

**Comment by bannanc** [comment]
> I think the molecule sets probably make the most sense to be here actually, including the oeb to mol2 script. We use them to test the smarty and smirky simulations, but they've also been used when developing the smirnoff force field

@davidlmobley I wrote that thinking I was on the openforcefield repo I think both of those things should be there. I'll see if I can revert both of these by one commit?
I'm not sure how to do that.

**Pull request merged**
