### PR TITLE
DrugBank torsion test from test_smirff99Frosst to smirff99Frosst

### PR DESCRIPTION
**Pull request by bannanc**
@cbayly13 and @davidlmobley 

I made a new directory in examples for now that has the DrugBank test, including the script I used to filter the DrugBank molecules by size and rather they contained metals. It's at [smarty/examples/test_smirff99Frosst](https://github.com/open-forcefield-group/smarty/tree/test_smirff99Frosst/examples/test_smirff99Frosst) 

I haven't run it for Bonds or Angles yet. In the first 10 molecules the missing torsions are cationic, aromatic nitrogen (real? maybe?) and phosphate groups that usually have a hydroxyl group something like P(=O)-O-H

### CODE REVIEW

**Comment by bannanc** [comment]
I updated convert_frcmod.py and I'm pretty certain it fixed the issue with 3+ fold torsions getting converted into the ffxml correctly. 
I made a comment above the relevant while loop in the code @davidlmobley if you want to see the change.

**Comment by bannanc** [comment]
I'm going to postpone this merge until the smirky sampler pull request #130 is merged because I have all of those changes here due to working on both sides of the project in one directory.

I anticipate the smirky merge happening before #136 will be ready anyway.

**Comment by bannanc** [comment]
@davidlmobley is it ok for me to just merge this and continue making changes in the smirff99Frosst branch?

**Comment by davidlmobley** [comment]
Yup, merging.

**Pull request merged**
