### PR TITLE
Add optional argument to allow bypassing of assertion on improper force term comparison

### PR DESCRIPTION
**Pull request by davidlmobley**
Uses https://github.com/choderalab/openmoltools/pull/234

### CODE REVIEW

**Comment by davidlmobley** [comment]
@jchodera - to get this to pass, I need a minor change in openmoltools to propagate to the omnia build. What's the latest to make sure this happens -- I cut a new release of openmoltools, and then it happens automatically? Or is there another step to take after that?

Thanks.

**Comment by jchodera** [comment]
Did you already make a PR for the openmoltools change?

If so, we need to cut a new minor or bugfix release of openmoltools and bump the conda recipe version. We should document that...

**Comment by davidlmobley** [comment]
It's already merged, yes.

I agree that documenting this -- and the process of getting things onto Omnia and into this general pipeline -- would be extremely helpful. Sooner or later I'll have to have get other people to do it and there are some parts of it that I'm still fuzzy on. I've set up Travis on repos now, so I'm comfortable with the testing and release part, but I'm still a bit unclear on how to get things onto Omnia (along with new dependencies they might need) and how to trigger getting new builds onto Omnia.

**Comment by jchodera** [comment]
My lab is working on documenting our software development and deployment practices:

https://github.com/choderalab/software-development

Right now, it's just a bunch of issues with writing assignments to tackle this week. If you see anything missing, feel free to mention what you would like to see in an issue.

I'll be working on the omnia build documentation. We can link to that from some standard developer docs how-to we include in each repository so it is clear how to contribute, cut a release, etc.

**Comment by jchodera** [comment]
For now, let me type up some notes about the release process.

**Comment by davidlmobley** [comment]
Hmm, another miniconda MD5 mismatch; did they update again?

**Comment by jchodera** [comment]
Sorry, I have a fix for this. Will update.

**Comment by davidlmobley** [comment]
When you do the fix in one place, @jchodera (i.e. even another repo) do you want to tag me and then I can propagate across open-forcefield-group repos with testing enabled?

**Comment by davidlmobley** [comment]
@jchodera - this is currently failing on py27 and py34 (but passing on py35) because of an issue with openmoltools that I don't understand at all. Specifically, the 0.73 changes to openmoltools -- which added a `skipImpropers` argument to `syscheck.check_force_parameters` seem not to be showing up for py27 and py34, which result in this error in those cases:

> ```
> syscheck.check_force_parameters(skipImpropers = skip_improper)
> ```
> 
>  TypeError: check_force_parameters() got an unexpected keyword argument 'skipImpropers'

However, things seem just fine for py35. (And tests past locally in py27 on my machine). I don't understand how this can be. Any insights?

**Comment by jchodera** [comment]
That's odd. The packages all went up [18 hours ago](https://anaconda.org/omnia/openmoltools/files?sort=time&sort_order=desc) for all versions of python.

**Comment by jchodera** [comment]
It's because you're [actually having `openmoltools 0.6.8` installed for testing](https://travis-ci.org/open-forcefield-group/smarty/jobs/172797162#L550):

```
    openmoltools-0.6.8         |           py27_1         4.3 MB  omnia
```

**Comment by jchodera** [comment]
I suggest you change [this line](https://github.com/open-forcefield-group/smarty/blob/master/devtools/conda-recipe/meta.yaml#L22) from

``` YAML
    - openmoltools
```

to

``` YAML
    - openmoltools >=0.7.3
```

if you really require versions 0.7.3 or later.

**Comment by davidlmobley** [comment]
Thanks, @jchodera ! I'd searched the travis logs and found it was pulling openmoltools 0.7.3 but apparently I didn't review carefully enough. Odd that it would pull 0.7.3 for py35 and 0.6.8 for the other python versions. I just pushed that change.

**Pull request merged**
