### PR TITLE
Validate/finalize implementation of impropers

### PR DESCRIPTION
**Pull request by davidlmobley**
This currently adds an IPython notebook looking at energies for benzene and o-xylene from parm@frosst and smirff99Frosst to validate the implementation of impropers (as per #62). It also provides (in `examples/testing/test_impropers`) an example modified smirff99Frosst which has been tweaked to have the same angle energies within the ring as parm99 for benzene (at the cost of an extra angle parameter) to aid with energy validation.

Before merged, this will also:
- [x] Divide six-fold (trefoil) impropers by six internally so that AMBER barrier heights can transfer in directly, as per https://github.com/open-forcefield-group/smarty/issues/51
- [x] Add automated testing of the improper implementation (i.e. on benzene) along with a minimal benzene ffxml file to enable this
- [x] Add check that impropers are impropers and propers are propers (#122)
- [x] Also test on molecule `CC(C)(C)c1ccccc1C(C)(C)C` which uses steric strain to induce significant improper energy (benzene and o-xylene don't).

I also fixed a small bug with an improper smirks provided in one of the tests (it was not being checked previously).

### CODE REVIEW

**Comment by davidlmobley** [comment]
This now resolves #51 in that the six-fold division is now taken care of internally.

**Comment by davidlmobley** [comment]
Resolves #122 by checking that no SMIRKS patterns for impropers are labeled as propers or vise versa.

**Comment by davidlmobley** [comment]
@bannanc -- can you try running the SMIRKS for propers/impropers through your chemical environments using the latest AlkEthOH ffxml? This PR is throwing an error in Travis because it can't recognize whether one of the torsions (proper or improper) is a proper or an improper. It could be that there is a typo, or it could be a problem with your environments.

The error is something like:

```
if OR[0] != '~':
IndexError: string index out of range
```

and it's thrown by `test_forcefield.py` on Travis.

The relevant code is in forcefield.py in this PR around line 1363 and is based on the code snippet you sent me, i.e.:

```
            # Check that the SMIRKS pattern matches the type it's supposed
            # to be (avoiding bugs wherein an improperly formed generic improper
            # overrides propers, for example)
            chemenv = env.ChemicalEnvironment(self.smirks)
            thistype = chemenv.getType()
            if thistype=='Torsion': thistype = 'Proper'
            if self.torsiontype != thistype:
                raise Exception("Error: SMIRKS pattern %s (parameter %s) does not specify a %s torsion, but it is supposed to." % (self.smirks, self.pid, self.torsiontype))
```

but apparently it's having trouble recognizing one or more of the SMIRKS patterns used in AlkEthOH.

**Comment by bannanc** [comment]
@davidlmobley  
Without looking at the details I can bet where the problem is. Currently my parsing expects SMIRKS input the same as environments output. That is there are no "embedded atoms" so it doesn't handle SMIRKS in the form `[#1$(*~[#6])]` yet. It just looks for the beginning and ends of atoms based on where the `']'` symbol is. 

I'm working on a plan to include this in our parsing, but I haven't incorporated it yet.

**Comment by davidlmobley** [comment]
Merging this, as now impropers are validated and functional, and testing is in place.

**Pull request merged**
