### PR TITLE
adding parent dictionary and output of hierarchy tree

### PR DESCRIPTION
**Pull request by bannanc**
Adds "parent" dictionary to track parents and children 

Since there are many methods that use the atom list, I decided it would be easier to introduce a dictionary since it only needs to be used in the implementation and the sample_atomtypes method. 

My next plan is to print the tree (hierarchy) at the end of a run, if it's verbose, but I haven't quite sorted the easiest way to do that yet. 

Addresses issue #34

### CODE REVIEW

**Comment by bannanc** [comment]
@davidlmobley 

Most recent commit prints 'tree' at the end of the run with output like this:

```
Atom type hierarchy:
[#1]
|   [#1&$(*~[#6])]
[#8]
|   [#8&H0]
[#6]
```

Later we can add something prettier, but it at least lets us see the hierarchy for now.

**Comment by bannanc** [comment]
@davidlmobley I added a gitignore file since this was still open. 
I think this is ready to go unless @jchodera wants to look at it.

**Comment by jchodera** [comment]
Looks good to me!

**Comment by davidlmobley** [comment]
Looks good to me, @bannanc . Maybe add a low priority issue (enhancement) to allow visualization of the tree via that python module noted elsewhere; it's not important now but eventually when we get to parm@frosst on the ZINC set it will probably be helpful. 

This also resolves issue #36 .

**Pull request merged**
