### PR TITLE
Add aromaticity model support as per 125

### PR DESCRIPTION
**Pull request by davidlmobley**
This adds aromaticity model support as per #125 . Also adds a version attribute at the same time.

C Bayly needs this ASAP so I'm trying to get something rough up immediately for him to use. I'll revisit it likely early next week to polish.

### CODE REVIEW

**Comment by davidlmobley** [comment]
We've verified that this works. On `c12c(cccc1)occ2` the bond 6-7 (among others) ends up different with and without the MDL aromaticity model in Chris's "super preliminary draft parm@frosst-y SMIRFF for bonds".

But, I have to run off for the weekend, so Bayly will be working/testing.

**Comment by jchodera** [comment]
Please add nosetests! "we've verified that this works" is not future proof!

**Comment by davidlmobley** [comment]
@jchodera - yes, will add nosetests. That's why this is still [WIP]. I've just been focused on getting things done which must be done now before implementing tests. :)

**Comment by davidlmobley** [comment]
Added tests verifying not just that it runs but also that the choice of aromaticity model has the desired effect. Should be ready to merge once it passes tests.

**Pull request merged**
