### PR TITLE
remove repeat molecules from smirky

### PR DESCRIPTION
**Pull request by bannanc**
* Addressing issue #253 to remove repeat molecules in smirky. 
      * Also removing repeat molecules from smarty
* updating the parse_odds_file function per issue #252 including a test on this function that is verbose.
* add jupyter notebook for testing timing as discussed in issue #251 

~@camizanette and @davidlmobley should we do the same in smarty?~ Yes

### CODE REVIEW

**Comment by davidlmobley** [comment]
@bannanc - yes, smarty should also not count repeat molecules multiple times (so they should be removed).

Tag me when you're ready for review.

**Comment by bannanc** [comment]
Well I was about to write something about this being ready to go, but I'll need to figure out what I broke in smarty first.

**Comment by bannanc** [comment]
@davidlmobley I think this one is ready now too

**Review by davidlmobley — APPROVED** [review]
Looks good to me! Thanks.

**Pull request merged**
