### PR TITLE
Added a method for focused atom searching

### PR DESCRIPTION
**Pull request by bannanc**
While this method might not get used beyond AlkEthOH, we believe it will help trouble shooting. WE should have new atom_sampler methods soon. 

It lead me to re-organize the parent dictionaries to include SMARTS and 'type-names'. 
There's also a bit of a reorganization for the run method (which also makes the use of the trajectory file a little more logical). 

This addresses issues #54 and #50

### CODE REVIEW

**Comment by bannanc** [comment]
heads up @davidlmobley , @camizanette and @cbayly13

**Comment by davidlmobley** [comment]
I can review in a bit, though note you need to update your branch to incorporate changes I pushed to master since you started working on this. (These all related to SMIRFF so there should be no conflicts).

**Comment by bannanc** [comment]
I did a git pull origin master before I made the pull request, but I'll double check. 

edit: I push to the remote branch again, I think it should be up to date now.

**Comment by bannanc** [comment]
Found what is causing the tests to fail, posting an update momentarily

**Comment by davidlmobley** [comment]
LGTM. Thanks, @bannanc .

**Comment by davidlmobley** [comment]
Well,that's weird, @bannanc - now that I merged, Travis is e-mailing me saying the build is broken. Not quite sure what's going on. Can you confirm that it still passes checks locally?

Thanks.

**Pull request merged**
