### PR TITLE
checking on tests, networkx, and small README update.

### PR DESCRIPTION
**Pull request by bannanc**
A while ago @davidlmobley asked me to check on smarty because he was getting notifications about the tests failing. I think this is likely due to networkx versions. I wanted to see the error here so I needed to open a PR. I thought I'd just make a small, unnoticeable change to the README, but then I noticed we didn't have installing openforcefield in the instructions (which you need for smirky)

### CODE REVIEW

**Comment by davidlmobley** [comment]
Thanks, @bannanc . Seems like the note about a better way to install via `conda` can also be removed too...?  Ping me when tests pass (and after addressing that if you like) and I can merge.

**Comment by bannanc** [comment]
@davidlmobley 
I tried to pin the networkx version as the initial errors seemed to be related to that. Now it says `ImportError: No module named 'pandas'`. We use pandas to process data csv files. Pandas are in the meta.yml file. Is there anything else that would cause this error?

**Comment by davidlmobley** [comment]
@bannanc - I know I've seen this before, but I also don't remember the solution. I'd cross-check against other software which requires pandas, such as `alchemlb` (http://github.com/alchemistry/alchemlyb) or there is probably much from the Chodera lab. Possibly `openforcefield` also requires it, I'd have to check.

**Comment by bannanc** [comment]
OK, I think I also saw this before, maybe it was in openforcefield (though I don't think it requires pandas...). I'll try looking at old PRs or the difference in the meta.yml files tomorrow.

**Comment by bannanc** [comment]
@davidlmobley 
I'm looking more closely, is it possible the openeye license is expired? 
Here's the complete error message:
```
$ cd devtools && nosetests -vv --nocapture --with-timer $PACKAGENAME && cd ..
nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
No module named simtk
Warning: Cannot import openeye toolkit; not all functionality will be available.
Failure: ImportError (No module named pandas) ... ERROR
======================================================================
ERROR: Failure: ImportError (No module named pandas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/nose/loader.py", line 407, in loadTestsFromName
    module = resolve_name(addr.module)
  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/nose/util.py", line 312, in resolve_name
    module = __import__('.'.join(parts_copy))
  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/smarty/__init__.py", line 16, in <module>
    from smarty.score_utils import *
  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/smarty/score_utils.py", line 2, in <module>
    import pandas as pd
ImportError: No module named pandas
nose.failure.Failure.runTest: 0.0002s
----------------------------------------------------------------------
Ran 1 test in 0.001s

```

**Comment by jchodera** [comment]
Your problem is in the recipe. See the [travis failure](https://travis-ci.org/open-forcefield-group/smarty/jobs/295121331#L717):
```
Error: bad character '=' in package name dependency 'networkx=1.11'
```
You need to fix [this line](https://github.com/open-forcefield-group/smarty/pull/257/files#diff-23fca1736cbf667a8319e570051bbe20R21) to read:
```
networkx ==1.11
```
Note the space before `==`

**Comment by bannanc** [comment]
Thank you @jchodera !!

**Comment by bannanc** [comment]
It looks like the problem with networkx is fixed with openforcefield being fixed. If one of you can review and merge that would be great.

**Comment by davidlmobley** [comment]
I have this on the list for today if I get any time in between meetings. Possibly between 1 and 2:30.

**Review by davidlmobley — APPROVED** [review]
Have you done an overall check of the repo (maybe grep the files?) to make sure "SMIRFF" doesn't occur? I thought we'd mostly eradicated SMIRFF but apparently it was still here fairly frequently.

Otherwise looks good; feel free to merge once checking the above.

**Comment by bannanc** [comment]
I can search the repo for SMIRFF. 
I spent a lot of time updating openforcefield when we switched names, but I guess we spent less time here. 
It is still in the smirky command line tool because I didn't want to change the command.

**Comment by davidlmobley** [comment]
I think just take a quick look and get anything easy; don't spend much time on it.

**Comment by bannanc** [comment]
@davidlmobley 
I just did a repo search, the only places it occurs now are in the `--smirff` command as a part of smirky.

**Comment by davidlmobley** [comment]
Thanks.

**Pull request merged**
