### PR TITLE
[WIP] Add sanity checking for topological bonds

### PR DESCRIPTION
**Pull request by jchodera**
Discussed in #147

### CODE REVIEW

**Comment by davidlmobley** [comment]
@jchodera - I'm working on a fix to this. Any preferences as to whether I do a PR into your branch, which would then update this PR, versus kill this PR and do a PR into master? (I've picked up from where you were in this branch.)

**Comment by jchodera** [comment]
Why not just make changes to this branch directly?

**Comment by davidlmobley** [comment]
Sure, if I can, er, figure out the right invocation to do that now that I've been working on a derivative branch. :) Otherwise I'll just PR to this one and then merge the PR straightaway.

**Comment by jchodera** [comment]
Oh, nevermind---do whatever is easiest then, like PR directly into `master` and close this.

**Comment by davidlmobley** [comment]
Closing, replaced by #155.

**Pull request closed without merging**
