### PR TITLE
Smirky example documentation update and file organization

### PR DESCRIPTION
**Pull request by bannanc**
@davidlmobley 

I moved all the smirky testing to google drive and updated the example/smirky README with a public link to the directory. 

The documentation in the smirky tests on google drive is still a work in progress, but I thought I would get the changes in here. There aren't any changes to code, just file reorganization and README docs in the examples.

### CODE REVIEW

**Comment by jchodera** [comment]
> I moved all the smirky testing to google drive and updated the example/smirky README with a public link to the directory.

Wait, what?

**Comment by davidlmobley** [comment]
@jchodera - she has about a gigabyte of output log files/graphs/etc from testing/exploration. It did not seem to be a good idea to post all of those on GitHub since it would make the repo awfully large without adding much value.

@bannanc - probably a good idea to provide a little more context for onlookers. :)

**Comment by jchodera** [comment]
> @jchodera - she has about a gigabyte of output log files/graphs/etc from testing/exploration. It did not seem to be a good idea to post all of those on GitHub since it would make the repo awfully large without adding much value.

Ah, I concur.
Could we leave input files/scripts in though?

**Comment by davidlmobley** [comment]
(To put it another way, @jchodera -- we think we need to focus on having useful examples/illustrations/etc. here in the public repo, but having all of our actual research content and analysis here is probably overkill and not particularly useful to most people and will take an unnecessarily large amount of space. Caitlin is working on cleaning that stuff up and organizing.)

You posted in the interim. Yes, I believe she still has all of the input files and scripts here. She's just moving results of tests...

**Comment by jchodera** [comment]
Sounds like a good plan. Thanks for the context!

**Comment by bannanc** [comment]
@jchodera - sorry, I should have provided more context. I'm getting ready for advancement so I've been trying to get my portion of the smirky experiments and tests organized for Camila and David to have easy access to, initially we thought the testing directory would be a good place for this, but as David mentioned, I have a lot of data, it seemed a bit bulky, without providing much useful information.  

All of the scripts and a documented set of input files with example output is still at examples/smirky with an explanation of how to use smirky in the README. I then link to the larger examples on a public Google Drive directory if people want to see more detailed tests.

**Pull request merged**
